### ISSUE TITLE
Check this please

### ISSUE THREAD

**Issue by IlluminatiFish** [Lisenaaaa/Rain-TEMP#25]
https://github.com/Lisenaaaa/Rain-TEMP/blob/5f83c9a488b4c4448c06afe5e50dbd5b2c4bb28f/src/listeners/thisisaminecraftdiscordnotacsgotradingdiscord.ts#L96

This would fail for any http prefixed url, please fix

**Comment by Lisenaaaa** [comment]
probably fixed in https://github.com/Lisenaaaa/Rain-TEMP/commit/0c1cd036248cbe0f7fa1018422b73a31cb19c201

**Comment by IlluminatiFish** [comment]
lgtm
