### ISSUE TITLE
Moved ip list to a gist instead of hardcoding it

### ISSUE THREAD

**Issue by IlluminatiFish** [Lisenaaaa/Rain-TEMP#30]
Swap this array out for the array hosted on the gist, so that Koxx12's plugin can also use the IP list https://github.com/Lisenaaaa/Rain-TEMP/blob/eb8d6e6cb999c07fc3539977c340cff48386320b/src/listeners/thisisaminecraftdiscordnotacsgotradingdiscord.ts#L27

Updates will only be pushed to the gist now https://gist.githubusercontent.com/IlluminatiFish/e49d4b3cea4daf5be6823f6416b274fa/raw/fd68ffb9a7151023ae76170b0da4c2e137f72062/blacklist.txt

**Comment by Lisenaaaa** [comment]
will do once i get home

**Comment by IlluminatiFish** [comment]
alright

**Comment by Lisenaaaa** [comment]
luckily i haven't updated it to that yet

**Comment by Lisenaaaa** [comment]
you can just send the link to the commit and github will do magic

https://github.com/Lisenaaaa/Rain-TEMP/commit/ac2467fb05479b42402b42d9234d6c9a92571e69%22%3E#ac246
